<script setup lang="ts">
const { t } = useLocale()
const { data: me, error: meError } = await useFetch('/api/auth/me'); if(meError.value) await navigateTo('/login')
const { data: cars, refresh: refreshCars } = await useFetch('/api/cars'); const { data: bookings, refresh: refreshBookings } = await useFetch('/api/bookings')
const brands = Object.keys((await import('#shared/catalog')).vehicleCatalog); const models=ref<string[]>([]); const make=ref('BMW'); const model=ref(''); const error=ref('')
async function addCar(){error.value='';try{await $fetch('/api/cars',{method:'POST',body:{make:make.value,model:model.value}});model.value='';await refreshCars()}catch(e:any){error.value=e?.data?.statusMessage==='CAR_LIMIT_REACHED'?t('carLimit'):e?.statusCode===503?t('dbUnavailable'):t('bookingFailed')}}
async function cancelBooking(id:string){try{await $fetch(`/api/bookings/${id}`,{method:'DELETE'});await refreshBookings()}catch(e:any){error.value=t('bookingFailed')}}
watch(make,async m=>{const {vehicleCatalog}=await import('#shared/catalog');models.value=[...(vehicleCatalog as any)[m]||[]]},{immediate:true})
</script>
<template><div><div class="flex items-center justify-between"><div><h1 class="text-3xl font-bold">{{ t('account') }}</h1><p class="mt-1 text-slate-600">{{me?.user?.name}} · {{me?.user?.phone}}</p></div><button class="rounded-xl border px-4 py-2" @click="$fetch('/api/auth/logout',{method:'POST'}).then(()=>navigateTo('/login'))">{{ t('logout') }}</button></div><p v-if="error" class="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{{error}}</p><section class="mt-8"><h2 class="text-xl font-bold">{{ t('myCars') }}</h2><div class="mt-3 grid gap-3 sm:grid-cols-2"><div v-for="car in cars?.cars" :key="car.id" class="rounded-2xl border bg-white p-4"><b>{{car.make}} {{car.model}}</b><p class="text-sm text-slate-500">{{car.category}}</p></div></div><div class="mt-4 rounded-2xl border bg-white p-4"><p class="font-semibold">{{ t('addCar') }}</p><div class="mt-3 grid gap-3 sm:grid-cols-2"><select v-model="make" class="rounded-xl border p-3"><option v-for="b in brands" :key="b">{{b}}</option></select><select v-model="model" class="rounded-xl border p-3"><option value="">{{ t('model') }}</option><option v-for="m in models" :key="m">{{m}}</option></select></div><button class="mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white" @click="addCar">{{ t('addCar') }}</button></div></section><section class="mt-10"><h2 class="text-xl font-bold">{{ t('upcoming') }}</h2><div class="mt-3 space-y-3"><div v-for="b in bookings?.upcoming" :key="b.id" class="rounded-2xl border bg-white p-4"><div class="flex flex-wrap justify-between gap-2"><b>{{b.booking_date}} · {{String(b.booking_time).slice(0,5)}}</b><span>{{(b.price_cents/100).toFixed(0)}} €</span></div><p>{{b.make}} {{b.model}}</p><p class="text-sm text-slate-500">{{b.status}}</p><button class="mt-2 text-sm underline" @click="cancelBooking(b.id)">{{ t('cancel') }}</button></div><p v-if="!bookings?.upcoming?.length" class="text-slate-500">{{ t('noUpcoming') }}</p></div></section><section class="mt-10"><h2 class="text-xl font-bold">{{ t('history') }}</h2><div class="mt-3 space-y-3"><div v-for="b in bookings?.history" :key="b.id" class="rounded-2xl border bg-white p-4"><div class="flex justify-between"><b>{{b.booking_date}} · {{String(b.booking_time).slice(0,5)}}</b><span>{{(b.price_cents/100).toFixed(0)}} €</span></div><p>{{b.make}} {{b.model}}</p><p class="text-sm text-slate-500">{{b.status}}</p></div><p v-if="!bookings?.history?.length" class="text-slate-500">{{ t('noHistory') }}</p></div></section><NuxtLink to="/booking" class="fixed bottom-6 right-6 rounded-full bg-slate-900 px-5 py-3 font-semibold text-white shadow-lg">{{ t('newBooking') }}</NuxtLink></div></template>
